### PR TITLE
Promisify Functions

### LINKED ISSUE #90: Promise based write/getBuffer
Currently, write needs callback.
I'd like to be able to do this:

```
image.getBuffer(Jimp.MIME_JPEG).then(function(buffer) {
  res.writeHead(200, {
     'Content-Type': Jimp.MIME_JPEG,
     'Content-Length': buffer.length
   });
   res.end(buffer);
})
```

### LINKED ISSUE #232: The write promise callback is called before file exists
I just noticed that when using the promise based API, at least the write method actually resolves before the file was created, which is probably not what one would expect.

### LINKED ISSUE #308: Jimp.create instead of new Jimp for clearer syntax [Feature request] [Breaking change]
Currently, in order to create new image, one need to do:
```
var newImage = new Jimp(256, 256, function (err, image) {
    // this image is 256 x 256, every pixel is set to 0x00000000 
});
```
but this code is horrible, the `newImage` itself is undefined forever, not even a promise. I propose to change to following:
```
Jimp.create(256, 256),then((img) => {
    img.write(path);
    // this image is 256 x 256, every pixel is set to 0x00000000
}).catch(err => console.dir(err));
```

Update:

I think sync version can still stay this way:
```
var newImage = new Jimp(256, 256);
// this image is 256 x 256, every pixel is set to 0x00000000 
```
but async version should be deprecated and removed from doc as the reason I described above.

### LINKED ISSUE #374: write, getBuffer, getBase64 can be Promised
When using `async/await`, it's good way to have `write, getBuffer, getBase64` to return a Promise in addition to callback.

Now I work around this:

```js
  await jimp.read(imagePath)
    .then(image=>image.rotate(90))
    .then(image=>new Promise(
      (res, rej)=>image.write(savePath, (err,ret)=> err ? rej(err) : res(ret))
    ))
```

### LINKED ISSUE #445: new Jimp as promise
I see quite a bit of chatter about promises across various issues on the repo but no where do I see a mention about making the `new Jimp()` work with promises so I'm creating an issue addressing that. Currently the only way to create a new Jimp image appears to be as follows, adopted from the docs:

```js
new Jimp(256, 256, function (err, image) {
  if(!err) {
    // this image is 256 x 256, every pixel is set to 0x00000000
    return console.log(image);
  }
  return console.error(err);
});
```

but with promises this could be enhanced to:

```js
new Jimp(256, 256).then((img) => {
  // this image is 256 x 256, every pixel is set to 0x00000000
  return console.log(image);
}).catch((err) => {
  return console.error(err);
});
```

This currently throws the error message `"(intermediate value).then is not a function"`.
***

Also an example when using async/await

```js
asyc run () {
  try {
    var image = await new Jimp(256, 256);
    return console.log(image);
  } catch (err) {
    return console.error(err);
  }
}
```

### PR DESCRIPTION
**Pull request by hipstersmoothie**
closes #232 - write now can return a promise
closes #90 - same as above and getBuffer can now be async
closes #374 - base64 can now be async
closes #308 closes #445 - Jimp.read can take all args that the constructor can. Jimp.create added for clearer syntax. No need to add promises to the jimp constructor.

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@oliver-moran If you just merge this one all #473 and #477 will be merged as well

**Comment by hipstersmoothie** [comment]
@oliver-moran and if this one gets merged 10 issues get closed all at once 😮

**Comment by hipstersmoothie** [comment]
I think I'm gonna change it from getBuffer(mime, 'async') to getBufferAsync(mime)

**Comment by hipstersmoothie** [comment]
@oliver-moran Just added the 'async' functions. They are tested and documented. Everythings runs fine. This should be ready to go!

**Comment by hipstersmoothie** [comment]
@edi9999 what do you think of this one? it gets makes of the requested functions promises without breaking the current api

**Comment by edi9999** [comment]
in this MR I find that the duplication in the code is not good for maintanability.

Things like Bluebird can do the automatic transformation from callback to Promises.

**Comment by hipstersmoothie** [comment]
So should I use bluebird to do this? Or you want users to do that? I think it would be better just to have it supported. The code isn’t really duplicated either. I factored out the main functionality of each function and the sync and a sync functions just call them in different ways

**Comment by hipstersmoothie** [comment]
@edi9999 Switched to an implementation that just calls the current functions and return a promise. Similar to `Jimp.read`. I believe we should provide this functionality and not make the user do it themselves. Since we return promises in a few other places, it makes sense to do it in the last few places we can.

**Comment by hipstersmoothie** [comment]
@edi9999 have i fixed your duplication concerns?

**Comment by edi9999** [comment]
You can even just do it like this : 

```
const promisify = (fun, ctx, args) => {
  return new Promise((resolve, reject) => {
    args.push((err, data) => {
      err && reject(err);
      resolve(data);
    });
    fun.apply(ctx, args);
  });
};

 writeAsync(path) {
        return promisify(this.write, this, [path]);
 }
```

This way the "promisification code" is just in one place.

**Comment by hipstersmoothie** [comment]
@edi9999 added `promisify` util function

**Comment by Favna** [comment]
I see this closes #445 and some talk about `Jimp.create` but I can't find [any documentation](https://github.com/oliver-moran/jimp#creating-new-images) on this new function nor (easily) find it in the code changes by the PR. Could you clarify the usage?

**Comment by hipstersmoothie** [comment]
You can just use `Jimp.read` to make a Jimp instance. It takes all the same args as the constructor. `Jimp.create` also exists but it just calls `Jimp.read`. I'll document it now

**Comment by septs** [comment]
Request update "jimp.d.ts" file defines.

**Comment by hipstersmoothie** [comment]
@septs what updates are you requesting ?

**Pull request merged**
