### PR TITLE
Added basic GIF support

### PR DESCRIPTION
**Pull request by NGPixel**
Added support for reading GIF files. The first frame is always selected for subsequent operations.

Based on [omggif](https://github.com/deanm/omggif) javascript implementation of GIF 89a decoder.

### CODE REVIEW

**Comment by jasonzissman** [comment]
I needed this exact feature and stumbled upon this pull request.  Tried it and it worked great for 7 or 8 different GIFs I had lying around.  Thanks!

**Comment by slidenerd** [comment]
You guys are gonna absolutely love this :) Here is your 100% native implementation of GIF using JIMP
```
var GIFEncoder = require('gifencoder');
var Jimp = require('jimp');
var fs = require('fs');

var encoder = new GIFEncoder(320, 240);
// stream the results as they are available into myanimated.gif 
encoder.createReadStream().pipe(fs.createWriteStream('myanimated.gif'));

encoder.start();
encoder.setRepeat(0);   // 0 for repeat, -1 for no-repeat 
encoder.setDelay(500);  // frame delay in ms 
encoder.setQuality(10); // image quality. 10 is default. 

// use node-canvas 
var image = new Jimp(320, 240, 0xff0000, function (err, image) {
    encoder.addFrame(image.bitmap.data)
    // use node-canvas 
    var image = new Jimp(320, 240, 0x00ff00, function (err, image) {
        encoder.addFrame(image.bitmap.data)
        // use node-canvas 
        var image = new Jimp(320, 240, 0x0000ff, function (err, image) {
            encoder.addFrame(image.bitmap.data)
            encoder.finish()
        });
    });
})

```

**Comment by oliver-moran** [comment]
Thank you so much. This is brilliant. I'm planning on doing a release this weekend. This will be included.

**Comment by cancerberoSgx** [comment]
@NGPixel  seems it currently doesn't support multiple frames / delay , etc right ? 

@slidenerd Thanks! Seems your library does support frames / animation. Any way of setting delay time ? Would be awesome if it support promises /you could use something similar to node's promisity in 'utils' should be simple to implement. 

Anyway, is there a "official" way of extracting or composing multiple frames of gif files ? Could samthing like @slidenerd  be included in the read me temporarily ? 

Thanks!

**Pull request merged**
