### PR TITLE
add omggif as dependency rather than file

### PR DESCRIPTION
**Pull request by hipstersmoothie**

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@edi9999 any comments?

**Comment by edi9999** [comment]
Looks good to me, but has conflicts now.

**Comment by hipstersmoothie** [comment]
@edi9999 

* fixed merge conflicts
* noticed that `index.js` was indented wrong and i think i was because of clashing tab widths in prettier and editorconfig. so i set prettier's tab width to 4 to match and reformatted `index.js`

**Comment by edi9999** [comment]
Yes, looks good to me !

**Pull request merged**
