### PR TITLE
Plugin crop/fix safety checks

### PR DESCRIPTION
**Pull request by jagaSto**
# What's Changing and Why

* safety checks for the `width` and `height` of `remainingPixels` are moved behind the `pixelsToCrop` sanitization, otherwise they lead to wrong values if the `pixelsToCrop` are negative

I encountered this in the following use case:
* when calling the `autocrop` function on an image, I specified a `leaveBorder` value that was larger than the number of pixels that were cropped from the image. This lead to incorrect values for `widthOfRemainingPixels` and `heightOfRemainingPixels`, as they use the negative values of `pixelsToCrop` instead of the sanitized ones.

`leaveBorder` is applied here:

https://github.com/oliver-moran/jimp/blob/736054ef1bea6b6fb03db3e75f05cd922a9c104f/packages/plugin-crop/src/index.js#L209-L213

`safety checks` are applied here:

https://github.com/oliver-moran/jimp/blob/736054ef1bea6b6fb03db3e75f05cd922a9c104f/packages/plugin-crop/src/index.js#L224-L234

Moving the safety checks _behind_ the sanitization leads to correct values.

**Note:** I was not able to build and test locally, due to [this issue](https://github.com/oliver-moran/jimp/issues/742).

## What else might be affected

* only the `crop` plugin is affected

## Tasks

- [x] Add tests
- [x] Update Documentation
- [x] Update `jimp.d.ts`
- [ ] Add [SemVer](https://semver.org/) Label

### CODE REVIEW

**Comment by jagaSto** [comment]
is this repo dead? 😢

**Comment by hipstersmoothie** [comment]
@jagaSto  please rebase so the CI runs. Getting this project set up with good CI/CD has been an issue. but now we have circleci setup (I think) so it should be easier to mange the project!

**Comment by jagaSto** [comment]
thx for the hint @hipstersmoothie, will fix the tests once I find the time. Do you have any insights into https://github.com/oliver-moran/jimp/issues/742 ? Running the tests locally is not working for me, which will make the process of debugging a bit more painful 🙃

**Comment by jagaSto** [comment]
@hipstersmoothie this is fixed now!

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v0.6.7 :rocket:

**Pull request merged**
