### PR TITLE
Feature Request #214 : option to disable EXIF auto-rotation

### PR DESCRIPTION
**Pull request by kminkler**

### CODE REVIEW

**Comment by geonanorch** [comment]
I am also interested in such a feature, because:
 - sometimes one would like to process pictures as-is
 - sometimes EXIF parsing seems buggy (see [issue 21](https://github.com/bwindels/exif-parser/issues/21) on the `exif-parser` project)

**Comment by oliver-moran** [comment]
Thank you. Planning on doing a release this weekend. This will be included.

**Comment by geonanorch** [comment]
Just tested: now images no longer automatically get rotated based on EXIF value (instead, `exifRotate()` must be called). Thank you!

**Comment by geonanorch** [comment]
for the records, the [issue in the EXIF library (#21)](https://github.com/bwindels/exif-parser/issues/21) was fixed recently, so calling `exifRotate()` should be safer now.

**Pull request merged**
