### PR TITLE
Fix autocrop

### PR DESCRIPTION
**Pull request by xlc**

### CODE REVIEW

**Comment by mradionov** [comment]
It fixes my issue too, would love to have this merged. Thanks!

**Comment by oliver-moran** [comment]
The autocrop function was rewritten by an ealier pull request. Could you look at the main branch and see if the code there fixes your issue? Thanks.

**Comment by xlc** [comment]
Current master fixed by issue. I removed my fixes and leave the test image update if you want to merge it.

**Comment by oliver-moran** [comment]
Thanks, @xlc. I've pulled in the updated test image.

**Comment by mradionov** [comment]
Works great, thank you!

**Pull request merged**
