### PR TITLE
Added dilation and erosion

### PR DESCRIPTION
**Pull request by Ojas-Gulati**
Uses a square kernel.
Also modified README.md to include function descriptions

### CODE REVIEW

**Comment by Ojas-Gulati** [comment]
If someone could write test-cases for this, that would be helpful, since I am running windows.

Input:
```
00000
0▴▴▴0
0▴▴▴0
0▴▴▴0
00000
```

Output:
00000
0▴▴▴▴
0▴▴▴▴
0▴▴▴▴
0▴▴▴▴

**Comment by Ojas-Gulati** [comment]
note to self:
 - fix by storing eroded data in array
 - make test cases

**Comment by hipstersmoothie** [comment]
Since this hasn't been worked on in a year I'm going to close this PR. Feel free to open another if you figure it out!

**Comment by JpEncausse** [comment]
Hello is there a plugin for erode / dilatation ?

**Pull request closed without merging**
