### PR TITLE
Switch from request to phin!

### PR DESCRIPTION
**Pull request by bdsomer**
[`request`](https://npmjs.com/package/request) is way too large and has way too many dependencies! Use [`phin`](https://npmjs.com/package/phin) instead!

### CODE REVIEW

**Comment by edi9999** [comment]
This is great and good to be merged imo

**Comment by ethanent** [comment]
Looks like a good implementation to me also. @oliver-moran?

**Comment by edi9999** [comment]
They are some conflicts in your PR, can you rebase your PR on master ?

**Comment by bdsomer** [comment]
Absolutely @edi9999!

**Comment by edi9999** [comment]
Thanks , merged !

**Pull request merged**
