### PR TITLE
intToRgba to intToRGBA in jimp.d.ts

### PR DESCRIPTION
**Pull request by from-nibly**

### CODE REVIEW

**Comment by Ojas-Gulati** [comment]
I suggest you don't remove intToRgba - keep it and also define a new function intToRGBA in the main js file and make it point to intToRgba.

**Comment by from-nibly** [comment]
intToRgba does not exist. is there a reason both cases should be supported? It will be more work and more confusing.

**Comment by Ojas-Gulati** [comment]
Ah, ok. I thought that you were renaming an old feature.

Though something like this is on another feature of jimp - check `greyscale()` and `grayscale()` - they both point to the same function in the main js file.

**Comment by patheticcockroach** [comment]
NB this is also fixed in this PR https://github.com/oliver-moran/jimp/pull/329 (which also covers a bunch of missing methods)

**Comment by edi9999** [comment]
Fixed by #329

**Pull request closed without merging**
