### PR TITLE
add ordered dithering

### PR DESCRIPTION
**Pull request by neophob**
hi, this function adds ordered dithering to jimp and combined color reduction for RGB565. maybe its too specific, then I would split this function up.

### CODE REVIEW

**Comment by oliver-moran** [comment]
Sounds great. I might just change the method name (it's pretty long).

You've updated the PNG library. I've no objections to that in principle. Just wondering what's better, etc. before I pull it in since it's a fundamental change?

**Comment by neophob** [comment]
Hi, yes feel free to update the name. The new png library is api compatible with the current version - but it's maintained and has more features - see https://github.com/lukeapage/pngjs2#comparison-table 
I'll create a new pull request which will allow to set specific png encoding options soon.

**Comment by oliver-moran** [comment]
> I'll create a new pull request which will allow to set specific png encoding options soon.

That would be great. Have you seen this:
https://github.com/oliver-moran/jimp/issues/25

**Comment by neophob** [comment]
Yes I do - I'll see what I can do - I'll keep this discussion in the other issue.

**Comment by oliver-moran** [comment]
Merged.

**Comment by oliver-moran** [comment]
@neophob I've called the method `image.dither64()`. Is that OK with you?

**Comment by neophob** [comment]
Thanks, well I thinh dither64 is a bit missleading, I would call it dither16 (because the image data is 16bit) or to make it more clear call it dither565

**Comment by oliver-moran** [comment]
Doh! Yes, 16-bit is what I meant! In my mind I was thinking 16-bit was more "user friendly" than 5-6-5. If you think `dither565` is better then, yup, let's go with that. I wanted to check with you before publishing.

I was also thinking it would be nice to have a suit of dithering methods, like here:
https://en.wikipedia.org/wiki/List_of_monochrome_and_RGB_palettes#Regular_RGB_palettes

That was another reason for `dither16` (so we could have `dither3`, `dither6`, etc. in time).

**Comment by neophob** [comment]
I think maybe it would make sense to add more dithering methods yes

**Comment by oliver-moran** [comment]
Changed to `image.dither565()` (and I made an undocumented reference of `image.dither16()`)

**Pull request closed without merging**
