### PR TITLE
Fix 'blit' and add 'circle' functions

### PR DESCRIPTION
**Pull request by An2An96**
The function 'blit' worked incorrectly when using images with transparency.
And also, add function 'circle', which makes the picture round shape

### CODE REVIEW

**Comment by zhepa** [comment]
да это сносно

**Comment by hipstersmoothie** [comment]
@An2An96 Can you split the circle function into another PR. Maybe a shape function would be more useful?

As for the blit function can i see the before and after?

**Comment by hipstersmoothie** [comment]
bug in blit being fixed in #593

**Comment by hipstersmoothie** [comment]
blit bug released in [v0.4.0](https://github.com/oliver-moran/jimp/releases/tag/v0.4.0)

**Comment by hipstersmoothie** [comment]
closing in favor of #594

**Pull request closed without merging**
