### PR TITLE
Bump to jpeg-js 0.4.4, and don't hard-lock on a specific version.

### LINKED ISSUE #1088: jpeg-js dependency is vulnerable
**Is your feature request related to a problem? Please describe.**
Current version of @jimp/jpeg has a dependency on a vulnerable version of jpeg-js, this is causing it to be flagged with our sec-ops

**Describe the solution you'd like**
bump the version of jpeg-js to 0.4.4

### PR DESCRIPTION
**Pull request by shahmirn**
# What's Changing and Why

Fixes #1088 

## Tasks

- [ ] Add tests
- [ ] Update Documentation
- [ ] Update `jimp.d.ts`
- [ ] Add [SemVer](https://semver.org/) Label

### CODE REVIEW

**Review by victorcsciandt — APPROVED** [review]

**Comment by chris-tuncap** [comment]
Can this PR please get merged?

**Review by chris-tuncap — APPROVED** [review]

**Comment by demsking** [comment]
`@jimp/types` should be defined as a dev dependency inside the [Jimp's package.json file](https://github.com/oliver-moran/jimp/blob/master/packages/jimp/package.json#L64)

**Comment by konstantinschuette** [comment]
> `@jimp/types` should be defined as a dev dependency inside the [Jimp's package.json file](https://github.com/oliver-moran/jimp/blob/master/packages/jimp/package.json#L64)

Thats correct, but it shouldn't be part of this PR.
Can someone please merge this PR?

**Review by GrantBirki — APPROVED** [review]

**Review by alanneves — APPROVED** [review]
LGTM

**Review by miranciandt — APPROVED** [review]

**Review by Mad-Chemist — APPROVED** [review]

**Comment by shahmirn** [comment]
So many approvals, but I guess no one has permission to merge it?

**Pull request closed without merging**
