### PR TITLE
A very basic rectangle drawing function

### PR DESCRIPTION
**Pull request by majdhajyehia**
## Updates: 
Adding a rectangle function for drawing a rectangle on any image by manipulating pixel by pixel, and with the ability to choose to fill or not to fill the rectangle.
for drawing a rectangle you need to pass these values as parameters: 
- [x] image - the image that you need to draw on.
- [x] x1 - the x axis of the first point
- [x] y1 - the y axis of the first point
- [x] x2 - the x axis of the second point
- [x] y2 - the y axis of the second point
- [x] height - the height of the rectangle
- [x] fill - a Boolean variable which is to fill or not

## What things will this affect: 
This function won't affect any of the other features or functions of the library, but it will just be an independent function which allows you to draw a rectangle .. also I will be working on other drawing features like drawing a line or a circle or a rectangle.
 ## features will be added soon:
- [x] Line drawing function.
- [ ] Circle drawing function.
- [ ] Triangle drawing function.
- [ ] The ability to choose the color and the width of the rectangle's border.
- [ ] Other things will be soon.

[rectangle.txt](https://github.com/oliver-moran/jimp/files/2813669/rectangle.txt)

### CODE REVIEW

**Comment by thebestdoctor** [comment]
Parameters that have a tick, means that they are must be given to the function for making it work.

**Comment by houd1ni** [comment]
Thank you for the fresh code! Is it a plugin or a bundled feature?

**Comment by BestDr** [comment]
I think it could be a bundled feature, but I will be working on it all the time, also I will make functions for line, circle, point and all of these also I will improve it to take less parameters and make the same job, also I will be working on all the drawing features to make the library better, that's because I see that it is so useful and an excllent library that will save lots of time of people writing code.

**Comment by hipstersmoothie** [comment]
@BestDr Hows the progress on this?

**Comment by BestDr** [comment]
I was so busy this peroid, so I couldn't make more things, but I will be working on it these few days.

**Comment by BestDr** [comment]
What do you think? Is it better to enhance the rectangle function or to continue making more shapes and forms?

**Comment by houd1ni** [comment]
> 
> 
> @BestDr Hows the progress on this?

Hi! ~40%. Close in TODO, depends on time again. Will write here when something is ready.

**Comment by houd1ni** [comment]
By the way, guys, press the like button here, if interested, - I'll try to make it faster C:

**Comment by BestDr** [comment]
@houd1ni I can't close anything in todo, I don't know why, if you know the reason please tell me.

**Comment by BestDr** [comment]
@houd1ni I will continue working on it after 3 or 4 days, because after 3 / 4 days I will have nothing to do, and I will finish everything, then I will have a lot of time for working on Jimp.
Sorry for this long delay, but I will make it as good as I can after I finish everything.

**Comment by leegee** [comment]
Was looking for a quickie on drawing rectangles, stumbled on this. If I read your post correctly, you are requiring more parameters than logically required to draw a rectangle. Top-left/bottom-right co-ords would suffice -- the others can be deduced from that, no?

**Comment by houd1ni** [comment]
@leegee  Looks, like you're right, moreover, I think it's better to comply the html5 canvas spec where possible.

**Comment by BestDr** [comment]
@leegee I will make another function that requires one point, width and height soon.
If you agree or if you see that this function will be useful please add a reaction on this comment.
By the way, also I can remove the height parameter here, I don't even know why I thought of adding it, I could simply subtract the y axis of the two points.
But anyways, I c made this before a long time, and I was busy, but I will continue working on it again if possible.
Thank you for your suggestion.

**Comment by leegee** [comment]
I think follow the HTML5 canvas spec if possible, as
https://github.com/oliver-moran/jimp/pull/699#issuecomment-535844848

**Comment by BestDr** [comment]
@leegee @houd1ni what do you mean by the HTML5 canvas specs? Because I only made this function with the features that Jimp originally offers.

**Comment by leegee** [comment]
As in use the same API

**Comment by BestDr** [comment]
@leegee Can you give me an example from this repository of a function or a features that uses the HTML5 Canvas specs?

**Comment by BestDr** [comment]
@leegee Removed the height parameter.
Do you prefer that I remove the whole function and make it with less parameters or that I make another function that has a different number of parameters?

**Comment by leegee** [comment]
I'm no-one but a passer-by, but I liked the other guy's comment about
keeping inline with the canvas methods, as they are streamlined and
probably familiar tomost users.

**Comment by BestDr** [comment]
Ok, then I will try to make based on the HTML5 Canvas, the problem that I personally didn't use the HTML5 features a lot before.
But I will do my best to do that.
Thank you for giving me some useful suggestions, even if you are a passer-by you gave me some points that are so important.

**Comment by GlitchyPSIX** [comment]
What's the current progress on this? I'm interested.

One could also try porting the drawing elements from another pkg called `pureimage`

**Comment by BestDr** [comment]
> What's the current progress on this? I'm interested.
> 
> One could also try porting the drawing elements from another pkg called `pureimage`

I haven't pushed any commits since 8 months ago, but if you're interested I will finish this during the next week.
But, I wanna get some advices if you have any.
And the number of parameters will be reduced if I continued working on it, the height parameter useless here because I already have two points, and the fill / background-color parameters will be made optional too.

**Comment by GlitchyPSIX** [comment]
> > What's the current progress on this? I'm interested.
> > One could also try porting the drawing elements from another pkg called `pureimage`
> 
> I haven't pushed any commits since 8 months ago, but if you're interested I will finish this during the next week.
> But, I wanna get some advices if you have any.
> And the number of parameters will be reduced if I continued working on it, the height parameter useless here because I already have two points, and the fill / background-color parameters will be made optional too.

I read the reply chain and saw you were looking for someone's implementation that mimicks the HTML5 Canvas spec
Lucky you, the package I mentioned that could be ported from (called [`pureimage`](https://github.com/joshmarinacci/node-pureimage)) is actually based in the Canvas spec but it's not as powerful as JIMP in its current state (which is why I suggested porting over) so you can take inspiration from her



> What do you think? Is it better to enhance the rectangle function or to continue making more shapes and forms?

I believe JIMP would be an even better choice for those that prefer no native dependencies for imaging if more shapes were to be included...

Rectangle, Circle/Ellipse and Path (connected points) are a few that come to mind that would be very useful

**Comment by Frustrated-Programmer** [comment]
I don't suppose this is still being worked on. I'm looking at making triangles, but the math for that will be difficult.

**Comment by GlitchyPSIX** [comment]
> I don't suppose this is still being worked on. I'm looking at making triangles, but the math for that will be difficult.

Honestly just making a path drawing function similar to HTML5 Canvas can solve all polygon related functionalities
After all to draw triangles in many base libraries you DO have to define 3 points and how those 3 points will be displayed (in case of 2d, fill and stroke, in case of 3d, color per vertex or stuff along those lines)

**Comment by BestDr** [comment]
@Frustrated-Programmer @GlitchyPSIX 
For now I am working on something full-time and it's really hard to work on both two things, but I might have a little bit of time to work on completing all the features I listed in my main commend (including ellipse, triangle and all kinds of shapes if possible), and I will tell you all here when about the progress once I find the time :) .

**Comment by BestDr** [comment]
@houd1ni I have finished the line function with an optimization algorithm, where do I have to push the changes? because I can't upload files or open pull requests and branches

**Comment by houd1ni** [comment]
@BestDr  Hi! Why don't you? Open the PR to oliver-moran/jimp pointing to this issue.

**Comment by BestDr** [comment]
@houd1ni I uploaded it in #908 , ignore the test.js file, I uploaded it by accident.

**Comment by hipstersmoothie** [comment]
The code for this really isn't mergable and doesn't follow the patterns in the repo. I'm happy to merge a path drawing plugin to jimp. This just isn't quite it yet

**Pull request closed without merging**
