### PR TITLE
Follow redirects

### LINKED ISSUE #775: Error: Could not find MIME for Buffer <null>
This is the same as [issue 643](https://github.com/oliver-moran/jimp/issues/643). However, the latter is closed and seems like it is dead despite people experiencing this issue still.  

# Expected Behavior

`Jimp.read` loads an image from a URL correctly.

# Current Behavior

Trying to read some images from certain URLs fails, throwing `Error: Could not find MIME for Buffer <null>`

# Failure Information (for bugs)

Whilst certain images load correctly, other consistently fail (a failing url will always fail, without exception).  
Example failing URL: https://s-media-cache-ak0.pinimg.com/736x/c9/8f/e1/c98fe17dc7de72bb29c34a0c79ef5762.jpg  

Trying to `Jimp.read` it 1000 times gives:
```
Called jimp.read() 1000 times.
  Failed: 1000.
  Succeeded: 0.
```

## Steps to Reproduce

Repo with a simple script to reproduce the error: https://github.com/codan84/jimp-bug

## Context

- Jimp Version: 0.6.4
- Operating System: OSX 10.14.3
- Node version: v10.16.2

## Failure Logs

```
{ Error: Could not find MIME for Buffer <null>
    at Jimp.parseBitmap (/Users/gruszd01/workspace/jimp-bug/node_modules/@jimp/core/dist/utils/image-bitmap.js:108:15)
    at Jimp.parseBitmap (/Users/gruszd01/workspace/jimp-bug/node_modules/@jimp/core/dist/index.js:498:32)
    at /Users/gruszd01/workspace/jimp-bug/node_modules/@jimp/core/dist/index.js:440:15
    at /Users/gruszd01/workspace/jimp-bug/node_modules/@jimp/core/dist/index.js:168:14
    at /Users/gruszd01/workspace/jimp-bug/node_modules/@jimp/core/dist/request.js:56:9
    at IncomingMessage.<anonymous> (/Users/gruszd01/workspace/jimp-bug/node_modules/phin/lib/phin.compiled.js:1:2100)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) methodName: 'constructor' }
```

### PR DESCRIPTION
**Pull request by SaWey**
Fixes #775

# What's Changing and Why
Automatically follow http redirects instead of erroring out.

## Tasks

- [x] Add tests
- [ ] Update Documentation
- [ ] Update `jimp.d.ts`
- [ ] Add [SemVer](https://semver.org/) Label

Published PR with canary version: `0.8.1-canary.789.460.0`

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@SaWey please fix lint and add a test if you can

**Comment by FridayJew** [comment]
I installed version with this changing and that solve my problem. 
Byffer error happen only if I try to read a file that is only partially downloaded.

I think it's good results.

**Comment by hipstersmoothie** [comment]
I'd still like a test so we don't break it in the future. Good to know that it solved the problem though!

**Comment by SaWey** [comment]
I can't seem to get the test environment setup on my windows machine.
Keep bothering mee about not finding '@jimp/test-utils' module when running the tests.

How would you see this test being setup? Start a custom server to send a 301 response when loading an image?
Because if we were to use an internet link, we're not sure it's going to stay online.

**Comment by andresmmujica** [comment]
Hi, I'm having an issue that probably will get fixed with this.   My url redirects to the actual image but Jimp/phin is reading as XML so it fails.  If I test with curl url it shows the xml if I test curl -L url it works like a charm, so please if this gets into Jimp would be awesome

**Comment by SaWey** [comment]
I was able to add a test with a local server to mock a 301 redirect.

**Comment by SaWey** [comment]
@hipstersmoothie any idea how I should tackle this testcase?
I don't know how to differentiate between browser and node running the test.

**Comment by SaWey** [comment]
@hipstersmoothie 
Can this patch be applied?

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v0.9.3 :rocket:

**Pull request merged**
