### PR TITLE
Added mask function

### PR DESCRIPTION
**Pull request by disordinary**
I've added a mask function at line 374, it's modelled after the blit function. If a pixel has an rgb balance of 0 then make it transparent.

You create a mask like: http://www.sccs.swarthmore.edu/users/05/zap/labs/E27/lab1/images/circle-mask.png and apply it to the image.

### CODE REVIEW

**Comment by oliver-moran** [comment]
Looks really good. I might make one change: setting the destination alpha channel to the average of the mask RGB. That way if all all are 0 then the alpha is transparent. If all are 255 then the alpha is opaque. And if somewhere in between the alpha is semi-transparent.

Like: http://carijansen.com/2004/07/25/layer-mask-from-grayscale-image/

How does that sound?

**Comment by disordinary** [comment]
Yeah, even better.

**Comment by oliver-moran** [comment]
I've modified it so that it masks based on opacity. Fully transparent pixels on the mask will be fully opaque on the source image. And fully opaque pixels on the mask will be fully transparent on the source image.

**Comment by oliver-moran** [comment]
Integrated and modified to mask based on the average pixel value.

**Comment by gerges** [comment]
@oliver-moran, if you mask based on the average pixel value, then creating a circular mask of an image isn't possible, correct? If I have a image with black where I cant the result to be hidden, then that will be averaged with whatever pixel in the source image?

**Pull request merged**
