### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by iamstarkov**
just few bump deps and change `pngjs` due deprecation message

### CODE REVIEW

**Comment by iamstarkov** [comment]
@oliver-moran can you help me?

**Comment by oliver-moran** [comment]
Thanks, @iamstarkov - I'll test this and do a publish over the weekend!

**Comment by iamstarkov** [comment]
@oliver-moran i tried to test my pr on my own because i saw tests folder, but there is empty `npm test` script, so i failed. can you describe the test flow or maybe add valid `npm test` so i can test my changes?

**Comment by oliver-moran** [comment]
The test script is pretty rudimentary. If you run this script through bash it will run a collection of scripts:

https://github.com/oliver-moran/jimp/blob/master/test/tests.sh

There are not actual "tests" apart from seeing if an exception is thrown. I do a manual inspection of the output of each script instead. If you feel like writing a proper test script, you are more than welcome!

**Comment by oliver-moran** [comment]
Released to NPM just now. Thanks!

**Comment by iamstarkov** [comment]
@oliver-moran take a look at https://github.com/mapbox/pixelmatch which have been created for image comparison

**Comment by oliver-moran** [comment]
Thanks @iamstarkov. I'll give pixel match a shot.

**Pull request merged**
